[project]
name = "itzy-mayo-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.115.12",
    "pydantic>=2.11.5",
    "uvicorn[standard]>=0.34.3",
]
